### ISSUE TITLE
Code style: пакет, в котором лежит файл

### ISSUE THREAD

**Issue by anastasiya-solodkaya** [Shemegol/solution_of_QuadraticEquation#7]
В коде указан пакет, однако файл физически не находится в нужной иерархии папок. Нужно с этим что-то сделать - либо убрать пакет, либо положить файл в правильную иерархию папок.

**Comment by Shemegol** [comment]
В Intellij Idea был создан проект с пакетом, а сюда я загрузил просто файл класса. В следующий раз буду всю иерархию загружать.

**Comment by anastasiya-solodkaya** [comment]
Да, лучше иерархией всей. :smile:
